// _ExportUI_EOArchive_English.java
// Generated by EnterpriseObjects palette at Sunday, February 5, 2006 12:43:49 AM Europe/Zurich

import com.webobjects.eoapplication.*;
import com.webobjects.eocontrol.*;
import com.webobjects.eointerface.*;
import com.webobjects.eointerface.swing.*;
import com.webobjects.eointerface.swing.EOTable._EOTableColumn;
import com.webobjects.foundation.*;
import java.awt.*;
import javax.swing.*;
import javax.swing.border.*;
import javax.swing.table.*;
import javax.swing.text.*;

public class _ExportUI_EOArchive_English extends com.webobjects.eoapplication.EOArchive {
    ArrayController _arrayController0, _arrayController1, _arrayController2, _arrayController3;
    IBHelpConnector _iBHelpConnector0, _iBHelpConnector1;
    ImageCell _imageCell0;
    ObjectController _objectController0;
    com.webobjects.eointerface.swing.EOForm _nsForm0;
    com.webobjects.eointerface.swing.EOFormCell _eoFormCell0;
    com.webobjects.eointerface.swing.EOFrame _eoFrame0, _eoFrame1, _eoFrame2;
    com.webobjects.eointerface.swing.EOImageView _nsImageView0, _nsImageView1, _nsImageView2;
    com.webobjects.eointerface.swing.EOTable _nsTableView0, _nsTableView1;
    com.webobjects.eointerface.swing.EOTable._EOTableColumn _eoTableColumn0, _eoTableColumn1;
    com.webobjects.eointerface.swing.EOTextArea _nsTextView0, _nsTextView1;
    com.webobjects.eointerface.swing.EOTextField _nsSearchField0, _nsTextField0, _nsTextField1, _nsTextField10, _nsTextField11, _nsTextField12, _nsTextField13, _nsTextField14, _nsTextField15, _nsTextField16, _nsTextField17, _nsTextField18, _nsTextField19, _nsTextField2, _nsTextField20, _nsTextField21, _nsTextField22, _nsTextField23, _nsTextField24, _nsTextField25, _nsTextField26, _nsTextField3, _nsTextField4, _nsTextField5, _nsTextField6, _nsTextField7, _nsTextField8, _nsTextField9;
    com.webobjects.eointerface.swing.EOView _nsBox0, _nsBox1, _nsBox2, _nsBox3, _nsBox4, _nsBox5, _nsBox6, _nsBox7, _nsCustomView0, _nsProgressIndicator0;
    javax.swing.JButton _nsButton0, _nsButton1, _nsButton10, _nsButton11, _nsButton12, _nsButton13, _nsButton14, _nsButton15, _nsButton16, _nsButton2, _nsButton3, _nsButton4, _nsButton5, _nsButton6, _nsButton7, _nsButton8, _nsButton9;
    javax.swing.JCheckBox _nsButton17;
    javax.swing.JComboBox _popup0, _popup1;
    javax.swing.JPanel _nsView0, _nsView1, _nsView2;
    javax.swing.JPasswordField _nsTextField27;

    public _ExportUI_EOArchive_English(Object owner, NSDisposableRegistry registry) {
        super(owner, registry);
    }

    protected void _construct() {
        Object owner = _owner();
        EOArchive._ObjectInstantiationDelegate delegate = (owner instanceof EOArchive._ObjectInstantiationDelegate) ? (EOArchive._ObjectInstantiationDelegate)owner : null;
        Object replacement;

        super._construct();

        _imageCell0 = (ImageCell)_registered(new ImageCell(), "");
        _nsCustomView0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "View1");
        _arrayController3 = (ArrayController)_registered(new ArrayController(), "CategoriesController");
        _arrayController2 = (ArrayController)_registered(new ArrayController(), "AlbumsController");
        _nsTextField26 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _nsTextField25 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");
        _nsTextField24 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsButton16 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton1");
        _iBHelpConnector1 = (IBHelpConnector)_registered(new IBHelpConnector(), "");
        _nsTextField23 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2111");
        _iBHelpConnector0 = (IBHelpConnector)_registered(new IBHelpConnector(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "cpgurlField")) != null)) {
            _nsTextField22 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField22");
        } else {
            _nsTextField22 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField4");
        }

        _nsTextField21 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsButton15 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton1");
        _nsButton14 = (javax.swing.JButton)_registered(new javax.swing.JButton("OK"), "NSButton");
        _nsTextField20 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField19 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField211");
        _objectController0 = (ObjectController)_registered(new ObjectController(), "PasswdProxy");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "passwdField")) != null)) {
            _nsTextField27 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JPasswordField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField27");
        } else {
            _nsTextField27 = (javax.swing.JPasswordField)_registered(new javax.swing.JPasswordField(), "NSTextField3");
        }

        _nsTextField18 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField21");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "usernameField")) != null)) {
            _nsTextField17 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField17");
        } else {
            _nsTextField17 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField");
        }

        _nsTextField16 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsImageView2 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "credentialsSheet")) != null)) {
            _eoFrame2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame2");
        } else {
            _eoFrame2 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "Credentials");
        }

        _nsView2 = (JPanel)_eoFrame2.getContentPane();

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progBar")) != null)) {
            _nsProgressIndicator0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsProgressIndicator0");
        } else {
            _nsProgressIndicator0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "1");
        }

        _nsButton13 = (javax.swing.JButton)_registered(new javax.swing.JButton("Cancel"), "NSButton");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progText")) != null)) {
            _nsTextField15 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField15");
        } else {
            _nsTextField15 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        }

        _nsTextField14 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsImageView1 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "progressSheet")) != null)) {
            _eoFrame1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame1");
        } else {
            _eoFrame1 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "ProgressSheet");
        }

        _nsView1 = (JPanel)_eoFrame1.getContentPane();
        _nsButton12 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove image"), "");
        _nsButton11 = (javax.swing.JButton)_registered(new javax.swing.JButton("Clear default"), "NSButton41");
        _nsButton10 = (javax.swing.JButton)_registered(new javax.swing.JButton("Make default"), "NSButton4");
        _nsTextField13 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1113");
        _nsBox7 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView1");
        _nsBox6 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox112");
        _nsTextField12 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11");
        _nsTextField11 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsTextField10 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1111");
        _nsBox5 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox4 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox111");
        _nsTextField9 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1115");
        _nsTextField8 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsTextField7 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField11131");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "imageView")) != null)) {
            _nsImageView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOImageView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsImageView0");
        } else {
            _nsImageView0 = (com.webobjects.eointerface.swing.EOImageView)_registered(new com.webobjects.eointerface.swing.EOImageView(), "");
        }

        _nsTextField6 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1112");
        _nsTextView1 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _nsButton9 = (javax.swing.JButton)_registered(new javax.swing.JButton("Apply Description to All"), "NSButton1");
        _nsButton8 = (javax.swing.JButton)_registered(new javax.swing.JButton("Apply Title to All"), "NSButton");
        _nsTextField5 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsBox3 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "settingsBox")) != null)) {
            _nsBox2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOView)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsBox2");
        } else {
            _nsBox2 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");
        }

        _nsButton7 = (javax.swing.JButton)_registered(new javax.swing.JButton("Apply Tag to All"), "NSButton3");
        _nsButton6 = (javax.swing.JButton)_registered(new javax.swing.JButton("Remove Tag from All"), "NSButton31");
        _nsButton5 = (javax.swing.JButton)_registered(new javax.swing.JButton("Apply Set to All"), "NSButton32");
        _nsButton4 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resizeWidth")) != null)) {
            _nsTextField4 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField4");
        } else {
            _nsTextField4 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField3");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resizeWidth.nextFocusableComponent")) != null)) {
            _nsTextField3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTextField3");
        } else {
            _nsTextField3 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField31");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "resizeHeight.nextFocusableComponent")) != null)) {
            _nsButton3 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton3");
        } else {
            _nsButton3 = (javax.swing.JButton)_registered(new javax.swing.JButton("Apply to All"), "NSButton2");
        }

        _eoTableColumn1 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tagController.table")) != null)) {
            _nsTableView1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView1");
        } else {
            _nsTableView1 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "tagController")) != null)) {
            _arrayController1 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (ArrayController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_arrayController1");
        } else {
            _arrayController1 = (ArrayController)_registered(new ArrayController(), "SelectionsTags");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "lastView")) != null)) {
            _nsButton2 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (javax.swing.JButton)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsButton2");
        } else {
            _nsButton2 = (javax.swing.JButton)_registered(new javax.swing.JButton(""), "");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "settingsBox.searchField")) != null)) {
            _nsSearchField0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTextField)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsSearchField0");
        } else {
            _nsSearchField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "");
        }

        _nsButton1 = (javax.swing.JButton)_registered(new javax.swing.JButton("Change"), "NSButton6");
        _nsButton17 = (javax.swing.JCheckBox)_registered(new javax.swing.JCheckBox("Open the album when export completes"), "NSButton42");
        _eoTableColumn0 = (com.webobjects.eointerface.swing.EOTable._EOTableColumn)_registered(new com.webobjects.eointerface.swing.EOTable._EOTableColumn(), "NSTableColumn");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "recordController.tableView")) != null)) {
            _nsTableView0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOTable)replacement;
            _replacedObjects.setObjectForKey(replacement, "_nsTableView0");
        } else {
            _nsTableView0 = (com.webobjects.eointerface.swing.EOTable)_registered(new com.webobjects.eointerface.swing.EOTable(), "NSTableView");
        }

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "recordController.tableView.dataSource")) != null)) {
            _arrayController0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (ArrayController)replacement;
            _replacedObjects.setObjectForKey(replacement, "_arrayController0");
        } else {
            _arrayController0 = (ArrayController)_registered(new ArrayController(), "ImageRecords");
        }

        _nsButton0 = (javax.swing.JButton)_registered(new javax.swing.JButton("OK"), "NSButton");
        _popup1 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton1");
        _eoFormCell0 = (com.webobjects.eointerface.swing.EOFormCell)_registered(new com.webobjects.eointerface.swing.EOFormCell(), "");
        _nsForm0 = (com.webobjects.eointerface.swing.EOForm)_registered(new com.webobjects.eointerface.swing.EOForm(1, 1, 1, 8), "NSForm1");
        _popup0 = (javax.swing.JComboBox)_registered(new javax.swing.JComboBox(), "NSPopUpButton");
        _nsTextField2 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField1");
        _nsTextField1 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField2");
        _nsTextView0 = (com.webobjects.eointerface.swing.EOTextArea)_registered(new com.webobjects.eointerface.swing.EOTextArea(), "NSTextView");
        _nsTextField0 = (com.webobjects.eointerface.swing.EOTextField)_registered(new com.webobjects.eointerface.swing.EOTextField(), "NSTextField111");
        _nsBox1 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSView");
        _nsBox0 = (com.webobjects.eointerface.swing.EOView)_registered(new com.webobjects.eointerface.swing.EOView(), "NSBox");

        if ((delegate != null) && ((replacement = delegate.objectForOutletPath(this, "albumsSheet")) != null)) {
            _eoFrame0 = (replacement == EOArchive._ObjectInstantiationDelegate.NullObject) ? null : (com.webobjects.eointerface.swing.EOFrame)replacement;
            _replacedObjects.setObjectForKey(replacement, "_eoFrame0");
        } else {
            _eoFrame0 = (com.webobjects.eointerface.swing.EOFrame)_registered(new com.webobjects.eointerface.swing.EOFrame(), "AlbumSelection");
        }

        _nsView0 = (JPanel)_eoFrame0.getContentPane();
    }

    protected void _awaken() {
        super._awaken();
        _nsButton16.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "albumsSheetCancel", _nsButton16), ""));

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _connect(_owner(), _eoFrame0, "albumsSheet");
        }

        if (_replacedObjects.objectForKey("_nsTextField22") == null) {
            _connect(_owner(), _nsTextField22, "cpgurlField");
        }

        _nsButton15.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "credentialsSheetCancel", _nsButton15), ""));
        _nsButton14.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "credentialsSheetOK", _nsButton14), ""));

        if (_replacedObjects.objectForKey("_nsTextField27") == null) {
            _connect(_owner(), _nsTextField27, "passwdField");
        }

        if (_replacedObjects.objectForKey("_nsTextField17") == null) {
            _connect(_owner(), _nsTextField17, "usernameField");
        }

        if (_replacedObjects.objectForKey("_eoFrame2") == null) {
            _connect(_owner(), _eoFrame2, "credentialsSheet");
        }

        if (_replacedObjects.objectForKey("_nsProgressIndicator0") == null) {
            _connect(_owner(), _nsProgressIndicator0, "progBar");
        }

        _nsButton13.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "cancelUpload", _nsButton13), ""));

        if (_replacedObjects.objectForKey("_nsTextField15") == null) {
            _connect(_owner(), _nsTextField15, "progText");
        }

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _connect(_owner(), _eoFrame1, "progressSheet");
        }

        if (_replacedObjects.objectForKey("_nsBox2") == null) {
            _connect(_owner(), _nsBox2, "settingsBox");
        }

        _nsButton12.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeSelectedImage", _nsButton12), ""));
        _nsButton11.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "clearDefaultSize", _nsButton11), ""));
        _nsButton10.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "setDefaultSize", _nsButton10), ""));

        if (_replacedObjects.objectForKey("_nsImageView0") == null) {
            _connect(_owner(), _nsImageView0, "imageView");
        }

        _nsButton9.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "applyDescriptionToAll", _nsButton9), ""));
        _nsButton8.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "applyTitleToAll", _nsButton8), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_owner(), _nsButton2, "lastView");
        }

        _nsButton7.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "addSelectedTagToAll", _nsButton7), ""));
        _nsButton6.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "removeSelectedTagFromAll", _nsButton6), ""));
        _nsButton5.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "applyCurrentTagsToAll", _nsButton5), ""));

        if (_replacedObjects.objectForKey("_arrayController1") == null) {
            _connect(_owner(), _arrayController1, "tagController");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_owner(), _nsTextField4, "resizeWidth");
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_nsTextField4, _owner(), "delegate");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_owner(), _nsTextField3, "resizeHeight");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_nsTextField3, _owner(), "delegate");
        }

        _nsButton3.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "applyCurrentScalingToAll", _nsButton3), ""));
        _nsButton1.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "showCredentialsSheet", _nsButton1), ""));

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_owner(), _nsTableView0, "firstView");
        }

        if (_replacedObjects.objectForKey("_arrayController0") == null) {
            _connect(_owner(), _arrayController0, "recordController");
        }

        _nsButton0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_owner(), "albumsSheetOK", _nsButton0), ""));
        _popup1.setModel(new javax.swing.DefaultComboBoxModel());
        _popup1.addItem("Item1");
        _popup1.addItem("Item2");
        _popup1.addItem("Item3");
        _popup0.setModel(new javax.swing.DefaultComboBoxModel());
        _popup0.addItem("Item1");
        _popup0.addItem("Item2");
        _popup0.addItem("Item3");
    }

    protected void _init() {
        super._init();
        if (!(_nsCustomView0.getLayout() instanceof EOViewLayout)) { _nsCustomView0.setLayout(new EOViewLayout()); }
        _nsBox2.setSize(610, 364);
        _nsBox2.setLocation(17, 5);
        ((EOViewLayout)_nsCustomView0.getLayout()).setAutosizingMask(_nsBox2, EOViewLayout.MinYMargin);
        _nsCustomView0.add(_nsBox2);
        _setFontForComponent(_nsTextField26, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField26.setEditable(false);
        _nsTextField26.setOpaque(false);
        _nsTextField26.setText("Description:");
        _nsTextField26.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField26.setSelectable(false);
        _nsTextField26.setEnabled(true);
        _nsTextField26.setBorder(null);
        _setFontForComponent(_nsTextField25, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField25.setEditable(false);
        _nsTextField25.setOpaque(false);
        _nsTextField25.setText("Category:");
        _nsTextField25.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField25.setSelectable(false);
        _nsTextField25.setEnabled(true);
        _nsTextField25.setBorder(null);
        _setFontForComponent(_nsTextField24, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField24.setEditable(false);
        _nsTextField24.setOpaque(false);
        _nsTextField24.setText("If you want to upload them to a new album, please enter its name and select the category in which to create it, with an optional description.");
        _nsTextField24.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField24.setSelectable(false);
        _nsTextField24.setEnabled(true);
        _nsTextField24.setBorder(null);
        _connect(_nsButton0, _popup0, "nextFocusableComponent");
        _setFontForComponent(_nsButton16, "Lucida Grande", 13, Font.PLAIN);
        _nsButton16.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField23, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField23.setEditable(false);
        _nsTextField23.setOpaque(false);
        _nsTextField23.setText("URL:\n");
        _nsTextField23.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField23.setSelectable(false);
        _nsTextField23.setEnabled(true);
        _nsTextField23.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField22") == null) {
            _setFontForComponent(_nsTextField22, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField22.setEditable(true);
            _nsTextField22.setOpaque(true);
            _nsTextField22.setText("");
            _nsTextField22.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField22.setSelectable(true);
            _nsTextField22.setEnabled(true);
        }

        _setFontForComponent(_nsTextField21, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField21.setEditable(false);
        _nsTextField21.setOpaque(false);
        _nsTextField21.setText("Please enter your username and password, and the\nURL of the Coppermine site to use (enter the base URL only)");
        _nsTextField21.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField21.setSelectable(false);
        _nsTextField21.setEnabled(true);
        _nsTextField21.setBorder(null);
        _setFontForComponent(_nsButton15, "Lucida Grande", 13, Font.PLAIN);
        _nsButton15.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton14, "Lucida Grande", 13, Font.PLAIN);
        _nsButton14.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField20, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField20.setEditable(false);
        _nsTextField20.setOpaque(false);
        _nsTextField20.setText("Passwords are stored in your Keychain");
        _nsTextField20.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField20.setSelectable(false);
        _nsTextField20.setEnabled(true);
        _nsTextField20.setBorder(null);
        _setFontForComponent(_nsTextField19, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField19.setEditable(false);
        _nsTextField19.setOpaque(false);
        _nsTextField19.setText("Password:");
        _nsTextField19.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField19.setSelectable(false);
        _nsTextField19.setEnabled(true);
        _nsTextField19.setBorder(null);
        _connect(_objectController0, _nsTextField27, "content");

        if (_replacedObjects.objectForKey("_nsTextField27") == null) {
            _setFontForComponent(_nsTextField27, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField27.setEditable(true);
            _nsTextField27.setOpaque(true);
            _nsTextField27.setText("");
            _nsTextField27.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField27.setEnabled(true);
        }

        _setFontForComponent(_nsTextField18, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField18.setEditable(false);
        _nsTextField18.setOpaque(false);
        _nsTextField18.setText("Username:");
        _nsTextField18.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField18.setSelectable(false);
        _nsTextField18.setEnabled(true);
        _nsTextField18.setBorder(null);

        if (_replacedObjects.objectForKey("_nsTextField17") == null) {
            _setFontForComponent(_nsTextField17, "Lucida Grande", 13, Font.PLAIN);
            _nsTextField17.setEditable(true);
            _nsTextField17.setOpaque(true);
            _nsTextField17.setText("");
            _nsTextField17.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField17.setSelectable(true);
            _nsTextField17.setEnabled(true);
        }

        _setFontForComponent(_nsTextField16, "Lucida Grande", 13, Font.PLAIN + Font.BOLD);
        _nsTextField16.setEditable(false);
        _nsTextField16.setOpaque(false);
        _nsTextField16.setText("Coppermine Login Details");
        _nsTextField16.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField16.setSelectable(false);
        _nsTextField16.setEnabled(true);
        _nsTextField16.setBorder(null);
        if (!(_nsView2.getLayout() instanceof EOViewLayout)) { _nsView2.setLayout(new EOViewLayout()); }
        _nsImageView2.setSize(70, 70);
        _nsImageView2.setLocation(13, 14);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsImageView2, EOViewLayout.MinYMargin);
        _nsView2.add(_nsImageView2);
        _nsTextField16.setSize(193, 17);
        _nsTextField16.setLocation(89, 14);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField16, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField16);
        _nsTextField17.setSize(248, 22);
        _nsTextField17.setLocation(180, 78);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField17, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField17);
        _nsTextField18.setSize(86, 17);
        _nsTextField18.setLocation(89, 81);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField18, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField18);
        _nsTextField27.setSize(248, 22);
        _nsTextField27.setLocation(180, 108);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField27, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField27);
        _nsTextField19.setSize(68, 17);
        _nsTextField19.setLocation(107, 111);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField19, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField19);
        _nsTextField20.setSize(210, 14);
        _nsTextField20.setLocation(177, 168);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField20, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField20);
        _nsButton14.setSize(71, 26);
        _nsButton14.setLocation(360, 196);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton14, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton14);
        _nsButton15.setSize(75, 26);
        _nsButton15.setLocation(278, 196);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsButton15, EOViewLayout.MinYMargin);
        _nsView2.add(_nsButton15);
        _nsTextField21.setSize(329, 31);
        _nsTextField21.setLocation(89, 39);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField21, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField21);
        _nsTextField22.setSize(248, 22);
        _nsTextField22.setLocation(180, 138);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField22, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField22);
        _nsTextField23.setSize(68, 17);
        _nsTextField23.setLocation(107, 141);
        ((EOViewLayout)_nsView2.getLayout()).setAutosizingMask(_nsTextField23, EOViewLayout.MinYMargin);
        _nsView2.add(_nsTextField23);

        if (_replacedObjects.objectForKey("_eoFrame2") == null) {
            _nsView2.setSize(440, 232);
            _eoFrame2.setTitle("Panel");
            _eoFrame2.setLocation(121, 33);
            _eoFrame2.setSize(440, 232);
        }

        _setFontForComponent(_nsButton13, "Lucida Grande", 13, Font.PLAIN);
        _nsButton13.setMargin(new Insets(0, 2, 0, 2));

        if (_replacedObjects.objectForKey("_nsTextField15") == null) {
            _setFontForComponent(_nsTextField15, "Lucida Grande", 11, Font.PLAIN);
            _nsTextField15.setEditable(false);
            _nsTextField15.setOpaque(false);
            _nsTextField15.setText("");
            _nsTextField15.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField15.setSelectable(false);
            _nsTextField15.setEnabled(true);
            _nsTextField15.setBorder(null);
        }

        _setFontForComponent(_nsTextField14, "Lucida Grande", 13, Font.PLAIN);
        _nsTextField14.setEditable(false);
        _nsTextField14.setOpaque(false);
        _nsTextField14.setText("Coppermine Export");
        _nsTextField14.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField14.setSelectable(false);
        _nsTextField14.setEnabled(true);
        _nsTextField14.setBorder(null);
        if (!(_nsView1.getLayout() instanceof EOViewLayout)) { _nsView1.setLayout(new EOViewLayout()); }
        _nsImageView1.setSize(70, 70);
        _nsImageView1.setLocation(10, 11);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsImageView1, EOViewLayout.MinYMargin);
        _nsView1.add(_nsImageView1);
        _nsTextField14.setSize(141, 17);
        _nsTextField14.setLocation(86, 11);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField14, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField14);
        _nsTextField15.setSize(396, 14);
        _nsTextField15.setLocation(86, 36);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsTextField15, EOViewLayout.MinYMargin);
        _nsView1.add(_nsTextField15);
        _nsButton13.setSize(75, 26);
        _nsButton13.setLocation(407, 92);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsButton13, EOViewLayout.MinYMargin);
        _nsView1.add(_nsButton13);
        _nsProgressIndicator0.setSize(394, 20);
        _nsProgressIndicator0.setLocation(86, 58);
        ((EOViewLayout)_nsView1.getLayout()).setAutosizingMask(_nsProgressIndicator0, EOViewLayout.MinYMargin);
        _nsView1.add(_nsProgressIndicator0);

        if (_replacedObjects.objectForKey("_eoFrame1") == null) {
            _nsView1.setSize(491, 128);
            _eoFrame1.setTitle("Panel");
            _eoFrame1.setLocation(93, 221);
            _eoFrame1.setSize(491, 128);
        }

        _setFontForComponent(_nsButton12, "Lucida Grande", 9, Font.PLAIN);
        _nsButton12.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton11, "Lucida Grande", 9, Font.PLAIN);
        _nsButton11.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsButton10, "Lucida Grande", 9, Font.PLAIN);
        _nsButton10.setMargin(new Insets(0, 2, 0, 2));
        _setFontForComponent(_nsTextField13, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField13.setEditable(false);
        _nsTextField13.setOpaque(false);
        _nsTextField13.setText("CopperExport v(version)");
        _nsTextField13.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField13.setSelectable(false);
        _nsTextField13.setEnabled(true);
        _nsTextField13.setBorder(null);
        if (!(_nsBox6.getLayout() instanceof EOViewLayout)) { _nsBox6.setLayout(new EOViewLayout()); }
        _nsBox7.setSize(125, 1);
        _nsBox7.setLocation(2, 2);
        ((EOViewLayout)_nsBox6.getLayout()).setAutosizingMask(_nsBox7, EOViewLayout.MinYMargin);
        _nsBox6.add(_nsBox7);
        _nsBox6.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField12, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField12.setEditable(false);
        _nsTextField12.setOpaque(false);
        _nsTextField12.setText("http://cpgurl.org/\n");
        _nsTextField12.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField12.setSelectable(true);
        _nsTextField12.setEnabled(true);
        _nsTextField12.setBorder(null);
        _setFontForComponent(_nsTextField11, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField11.setEditable(false);
        _nsTextField11.setOpaque(false);
        _nsTextField11.setText("username");
        _nsTextField11.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField11.setSelectable(true);
        _nsTextField11.setEnabled(true);
        _nsTextField11.setBorder(null);
        _setFontForComponent(_nsTextField10, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField10.setEditable(false);
        _nsTextField10.setOpaque(false);
        _nsTextField10.setText("Uploading to:");
        _nsTextField10.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField10.setSelectable(false);
        _nsTextField10.setEnabled(true);
        _nsTextField10.setBorder(null);
        if (!(_nsBox4.getLayout() instanceof EOViewLayout)) { _nsBox4.setLayout(new EOViewLayout()); }
        _nsBox5.setSize(125, 1);
        _nsBox5.setLocation(2, 2);
        ((EOViewLayout)_nsBox4.getLayout()).setAutosizingMask(_nsBox5, EOViewLayout.MinYMargin);
        _nsBox4.add(_nsBox5);
        _nsBox4.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 13, Font.PLAIN));
        _setFontForComponent(_nsTextField9, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField9.setEditable(false);
        _nsTextField9.setOpaque(false);
        _nsTextField9.setText("Size:");
        _nsTextField9.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField9.setSelectable(false);
        _nsTextField9.setEnabled(true);
        _nsTextField9.setBorder(null);
        _setFontForComponent(_nsTextField8, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField8.setEditable(false);
        _nsTextField8.setOpaque(false);
        _nsTextField8.setText("Uploading as:");
        _nsTextField8.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField8.setSelectable(false);
        _nsTextField8.setEnabled(true);
        _nsTextField8.setBorder(null);
        _setFontForComponent(_nsTextField7, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField7.setEditable(false);
        _nsTextField7.setOpaque(false);
        _nsTextField7.setText("x");
        _nsTextField7.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField7.setSelectable(false);
        _nsTextField7.setEnabled(true);
        _nsTextField7.setBorder(null);
        _setFontForComponent(_nsTextField6, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField6.setEditable(false);
        _nsTextField6.setOpaque(false);
        _nsTextField6.setText("Title:");
        _nsTextField6.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField6.setSelectable(false);
        _nsTextField6.setEnabled(true);
        _nsTextField6.setBorder(null);
        _connect(_nsTableView0, _nsTextField5, "nextFocusableComponent");
        _nsTextView1.setEditable(true);
        _nsTextView1.setOpaque(true);
        _nsTextView1.setText("");
        _connect(_nsTextView1, _nsButton9, "nextFocusableComponent");
        _setFontForComponent(_nsButton9, "Lucida Grande", 9, Font.PLAIN);
        _nsButton9.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsButton8, _nsButton9, "nextFocusableComponent");
        _setFontForComponent(_nsButton8, "Lucida Grande", 9, Font.PLAIN);
        _nsButton8.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsTextField5, _nsButton8, "nextFocusableComponent");
        _setFontForComponent(_nsTextField5, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField5.setEditable(true);
        _nsTextField5.setOpaque(true);
        _nsTextField5.setText("");
        _nsTextField5.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField5.setSelectable(true);
        _nsTextField5.setEnabled(true);
        if (!(_nsBox3.getLayout() instanceof EOViewLayout)) { _nsBox3.setLayout(new EOViewLayout()); }
        _nsTableView0.setSize(102, 297);
        _nsTableView0.setLocation(8, 30);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTableView0, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTableView0);
        _nsTextField5.setSize(312, 15);
        _nsTextField5.setLocation(148, 58);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField5, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField5);
        _nsTextField6.setSize(27, 11);
        _nsTextField6.setLocation(116, 61);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField6, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField6);
        _nsTextView1.setSize(341, 79);
        _nsTextView1.setLocation(118, 81);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextView1, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextView1);
        _nsButton8.setSize(121, 16);
        _nsButton8.setLocation(471, 58);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton8, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton8);
        _nsButton9.setSize(121, 16);
        _nsButton9.setLocation(471, 81);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton9, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton9);
        _nsImageView0.setSize(206, 156);
        _nsImageView0.setLocation(115, 174);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsImageView0, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsImageView0);
        _nsTextField4.setSize(31, 15);
        _nsTextField4.setLocation(146, 335);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField4, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField4);
        _nsTextField3.setSize(31, 15);
        _nsTextField3.setLocation(197, 335);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField3, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField3);
        _nsTextField7.setSize(10, 11);
        _nsTextField7.setLocation(182, 336);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField7, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField7);
        _nsButton3.setSize(68, 16);
        _nsButton3.setLocation(236, 335);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton3, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton3);
        _nsTableView1.setSize(143, 150);
        _nsTableView1.setLocation(333, 177);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTableView1, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTableView1);
        _nsButton2.setSize(23, 21);
        _nsButton2.setLocation(504, 307);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton2, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton2);
        _nsButton4.setSize(23, 21);
        _nsButton4.setLocation(482, 307);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton4, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton4);
        _nsButton7.setSize(109, 16);
        _nsButton7.setLocation(483, 177);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton7, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton7);
        _nsButton6.setSize(109, 16);
        _nsButton6.setLocation(483, 199);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton6, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton6);
        _nsButton5.setSize(109, 16);
        _nsButton5.setLocation(483, 221);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton5, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton5);
        _nsButton17.setSize(198, 17);
        _nsButton17.setLocation(402, 6);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton17, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton17);
        _nsTextField8.setSize(64, 11);
        _nsTextField8.setLocation(116, 9);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField8, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField8);
        _nsButton1.setSize(50, 16);
        _nsButton1.setLocation(339, 8);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton1, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton1);
        _nsTextField9.setSize(25, 11);
        _nsTextField9.setLocation(116, 336);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField9, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField9);
        _nsBox4.setSize(472, 5);
        _nsBox4.setLocation(118, 166);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsBox4, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsBox4);
        _nsSearchField0.setSize(102, 15);
        _nsSearchField0.setLocation(9, 7);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsSearchField0, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsSearchField0);
        _nsTextField10.setSize(64, 11);
        _nsTextField10.setLocation(116, 27);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField10, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField10);
        _nsTextField11.setSize(129, 14);
        _nsTextField11.setLocation(182, 7);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField11, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField11);
        _nsTextField12.setSize(412, 14);
        _nsTextField12.setLocation(182, 25);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField12, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField12);
        _nsBox6.setSize(475, 5);
        _nsBox6.setLocation(118, 45);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsBox6, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsBox6);
        _nsTextField13.setSize(193, 11);
        _nsTextField13.setLocation(404, 341);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsTextField13, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsTextField13);
        _nsButton10.setSize(74, 16);
        _nsButton10.setLocation(313, 335);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton10, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton10);
        _nsButton11.setSize(73, 16);
        _nsButton11.setLocation(394, 335);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton11, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton11);
        _nsButton12.setSize(102, 20);
        _nsButton12.setLocation(8, 332);
        ((EOViewLayout)_nsBox3.getLayout()).setAutosizingMask(_nsButton12, EOViewLayout.MinYMargin);
        _nsBox3.add(_nsButton12);

        if (_replacedObjects.objectForKey("_nsBox2") == null) {
            if (!(_nsBox2.getLayout() instanceof EOViewLayout)) { _nsBox2.setLayout(new EOViewLayout()); }
            _nsBox3.setSize(606, 360);
            _nsBox3.setLocation(2, 2);
            ((EOViewLayout)_nsBox2.getLayout()).setAutosizingMask(_nsBox3, EOViewLayout.MinYMargin);
            _nsBox2.add(_nsBox3);
            _nsBox2.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        }

        if (_replacedObjects.objectForKey("_nsBox2") == null) {
            _connect(_nsBox2, _nsSearchField0, "searchField");
        }

        _connect(_nsTableView1, _nsButton7, "nextFocusableComponent");
        _setFontForComponent(_nsButton7, "Lucida Grande", 9, Font.PLAIN);
        _nsButton7.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsButton7, _nsButton6, "nextFocusableComponent");
        _setFontForComponent(_nsButton6, "Lucida Grande", 9, Font.PLAIN);
        _nsButton6.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsButton6, _nsButton5, "nextFocusableComponent");
        _setFontForComponent(_nsButton5, "Lucida Grande", 9, Font.PLAIN);
        _nsButton5.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsButton5, _nsButton4, "nextFocusableComponent");
        _connect(_nsButton4, _nsButton2, "nextFocusableComponent");
        _setFontForComponent(_nsButton4, "Lucida Grande", 10, Font.PLAIN);
        _nsButton4.setMargin(new Insets(0, 2, 0, 2));
        _nsButton4.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController1, "add", _nsButton4), ""));

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _setFontForComponent(_nsTextField4, "Lucida Grande", 9, Font.PLAIN);
            _nsTextField4.setEditable(true);
            _nsTextField4.setOpaque(true);
            _nsTextField4.setText("9999");
            _nsTextField4.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField4.setSelectable(true);
            _nsTextField4.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField4") == null) {
            _connect(_nsTextField4, _nsTextField3, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _setFontForComponent(_nsTextField3, "Lucida Grande", 9, Font.PLAIN);
            _nsTextField3.setEditable(true);
            _nsTextField3.setOpaque(true);
            _nsTextField3.setText("9999");
            _nsTextField3.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsTextField3.setSelectable(true);
            _nsTextField3.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsTextField3") == null) {
            _connect(_nsTextField3, _nsButton3, "nextFocusableComponent");
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _setFontForComponent(_nsButton3, "Lucida Grande", 9, Font.PLAIN);
            _nsButton3.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton3") == null) {
            _connect(_nsButton3, _nsTableView1, "nextFocusableComponent");
        }

        _eoTableColumn1.setMinWidth(40);
        _eoTableColumn1.setMaxWidth(1000);
        _eoTableColumn1.setPreferredWidth(127);
        _eoTableColumn1.setWidth(127);
        _eoTableColumn1.setResizable(true);
        _eoTableColumn1.setHeaderValue("");
        if ((_eoTableColumn1.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn1.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView1") == null) {
            _nsTableView1.table().addColumn(_eoTableColumn1);
            _setFontForComponent(_nsTableView1.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView1.table().setRowHeight(20);
        }

        if (_replacedObjects.objectForKey("_arrayController1") == null) {
            _connect(_arrayController1, _nsTableView1, "table");
        }

        _nsButton2.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController1, "remove", _nsButton2), ""));

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _setFontForComponent(_nsButton2, "Lucida Grande", 10, Font.PLAIN);
            _nsButton2.setMargin(new Insets(0, 2, 0, 2));
        }

        if (_replacedObjects.objectForKey("_nsButton2") == null) {
            _connect(_nsButton2, _nsSearchField0, "nextFocusableComponent");
        }

        _nsSearchField0.addActionListener((com.webobjects.eointerface.swing.EOControlActionAdapter)_registered(new com.webobjects.eointerface.swing.EOControlActionAdapter(_arrayController0, "search", _nsSearchField0), ""));

        if (_replacedObjects.objectForKey("_nsSearchField0") == null) {
            _setFontForComponent(_nsSearchField0, "Lucida Grande", 9, Font.PLAIN);
            _nsSearchField0.setEditable(true);
            _nsSearchField0.setOpaque(true);
            _nsSearchField0.setText("");
            _nsSearchField0.setHorizontalAlignment(javax.swing.JTextField.LEFT);
            _nsSearchField0.setSelectable(true);
            _nsSearchField0.setEnabled(true);
        }

        if (_replacedObjects.objectForKey("_nsSearchField0") == null) {
            _connect(_nsSearchField0, _nsButton1, "nextFocusableComponent");
        }

        _setFontForComponent(_nsButton1, "Lucida Grande", 9, Font.PLAIN);
        _nsButton1.setMargin(new Insets(0, 2, 0, 2));
        _connect(_nsButton1, _nsButton17, "nextFocusableComponent");
        _setFontForComponent(_nsButton17, "Lucida Grande", 9, Font.PLAIN);
        _connect(_nsButton17, _nsTableView0, "nextFocusableComponent");

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _connect(_nsTableView0, _arrayController0, "dataSource");
        }

        _eoTableColumn0.setMinWidth(8);
        _eoTableColumn0.setMaxWidth(1000);
        _eoTableColumn0.setPreferredWidth(86);
        _eoTableColumn0.setWidth(86);
        _eoTableColumn0.setResizable(true);
        _eoTableColumn0.setHeaderValue("");
        if ((_eoTableColumn0.getHeaderRenderer() != null)) {
        	((DefaultTableCellRenderer)(_eoTableColumn0.getHeaderRenderer())).setHorizontalAlignment(javax.swing.JTextField.LEFT);
        }

        if (_replacedObjects.objectForKey("_nsTableView0") == null) {
            _nsTableView0.table().addColumn(_eoTableColumn0);
            _setFontForComponent(_nsTableView0.table().getTableHeader(), "Lucida Grande", 11, Font.PLAIN);
            _nsTableView0.table().setRowHeight(43);
        }

        if (_replacedObjects.objectForKey("_arrayController0") == null) {
            _connect(_arrayController0, _nsTableView0, "tableView");
        }

        _setFontForComponent(_nsButton0, "Lucida Grande", 13, Font.PLAIN);
        _nsButton0.setMargin(new Insets(0, 2, 0, 2));
        _connect(_popup1, _nsButton0, "nextFocusableComponent");
        _setFontForComponent(_popup1, "Lucida Grande", 13, Font.PLAIN);
        _connect(_nsForm0, _popup1, "nextFocusableComponent");
        _setFontForComponent(_eoFormCell0, "Lucida Grande", 13, Font.PLAIN);
        _eoFormCell0.setTitle("Album name:");
        _eoFormCell0.setTitleWidth(93);
        _eoFormCell0.fieldComponent().setPreferredSize(new Dimension(2, 22));
        _eoFormCell0.titleComponent().setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _eoFormCell0.setSize(0, 0);
        _eoFormCell0.setLocation(-1, 0);
        _nsForm0.add(_eoFormCell0);
        _setFontForComponent(_nsForm0, "Lucida Grande", 13, Font.PLAIN);
        _connect(_popup0, _nsForm0, "nextFocusableComponent");
        _setFontForComponent(_popup0, "Lucida Grande", 13, Font.PLAIN);
        _setFontForComponent(_nsTextField2, "Lucida Grande", 11, Font.PLAIN);
        _nsTextField2.setEditable(false);
        _nsTextField2.setOpaque(false);
        _nsTextField2.setText("Please select the album to which you wish to upload your pictures.");
        _nsTextField2.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField2.setSelectable(false);
        _nsTextField2.setEnabled(true);
        _nsTextField2.setBorder(null);
        _setFontForComponent(_nsTextField1, "Lucida Grande", 13, Font.PLAIN + Font.BOLD);
        _nsTextField1.setEditable(false);
        _nsTextField1.setOpaque(false);
        _nsTextField1.setText("Destination album");
        _nsTextField1.setHorizontalAlignment(javax.swing.JTextField.LEFT);
        _nsTextField1.setSelectable(false);
        _nsTextField1.setEnabled(true);
        _nsTextField1.setBorder(null);
        _nsTextView0.setEditable(true);
        _nsTextView0.setOpaque(true);
        _nsTextView0.setText("");
        _setFontForComponent(_nsTextField0, "Lucida Grande", 9, Font.PLAIN);
        _nsTextField0.setEditable(false);
        _nsTextField0.setOpaque(false);
        _nsTextField0.setText("(Optional)");
        _nsTextField0.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        _nsTextField0.setSelectable(false);
        _nsTextField0.setEnabled(true);
        _nsTextField0.setBorder(null);
        if (!(_nsBox1.getLayout() instanceof EOViewLayout)) { _nsBox1.setLayout(new EOViewLayout()); }
        _nsTextField0.setSize(104, 11);
        _nsTextField0.setLocation(-9, 123);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextField0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextField0);
        _nsTextView0.setSize(310, 56);
        _nsTextView0.setLocation(99, 101);
        ((EOViewLayout)_nsBox1.getLayout()).setAutosizingMask(_nsTextView0, EOViewLayout.MinYMargin);
        _nsBox1.add(_nsTextView0);
        if (!(_nsBox0.getLayout() instanceof EOViewLayout)) { _nsBox0.setLayout(new EOViewLayout()); }
        _nsBox1.setSize(416, 165);
        _nsBox1.setLocation(2, 15);
        ((EOViewLayout)_nsBox0.getLayout()).setAutosizingMask(_nsBox1, EOViewLayout.MinYMargin);
        _nsBox0.add(_nsBox1);
        _nsBox0.setBorder(new com.webobjects.eointerface.swing._EODefaultBorder("", true, "Lucida Grande", 11, Font.PLAIN));
        if (!(_nsView0.getLayout() instanceof EOViewLayout)) { _nsView0.setLayout(new EOViewLayout()); }
        _nsBox0.setSize(420, 182);
        _nsBox0.setLocation(5, 83);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsBox0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsBox0);
        _nsTextField1.setSize(139, 17);
        _nsTextField1.setLocation(11, 14);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField1, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField1);
        _nsTextField2.setSize(410, 22);
        _nsTextField2.setLocation(11, 39);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField2, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField2);
        _popup0.setSize(403, 26);
        _popup0.setLocation(15, 59);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup0, EOViewLayout.MinYMargin);
        _nsView0.add(_popup0);
        _nsButton0.setSize(71, 26);
        _nsButton0.setLocation(350, 268);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton0);
        _nsButton16.setSize(75, 26);
        _nsButton16.setLocation(270, 268);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsButton16, EOViewLayout.MinYMargin);
        _nsView0.add(_nsButton16);
        _nsTextField24.setSize(410, 32);
        _nsTextField24.setLocation(11, 102);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField24, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField24);
        _nsForm0.setSize(405, 23);
        _nsForm0.setLocation(13, 137);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsForm0, EOViewLayout.MinYMargin);
        _nsView0.add(_nsForm0);
        _popup1.setSize(310, 26);
        _popup1.setLocation(108, 166);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_popup1, EOViewLayout.MinYMargin);
        _nsView0.add(_popup1);
        _nsTextField25.setSize(114, 17);
        _nsTextField25.setLocation(-12, 169);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField25, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField25);
        _nsTextField26.setSize(114, 17);
        _nsTextField26.setLocation(-12, 199);
        ((EOViewLayout)_nsView0.getLayout()).setAutosizingMask(_nsTextField26, EOViewLayout.MinYMargin);
        _nsView0.add(_nsTextField26);

        if (_replacedObjects.objectForKey("_eoFrame0") == null) {
            _nsView0.setSize(430, 304);
            _eoFrame0.setTitle("Destination Album");
            _eoFrame0.setLocation(207, 18);
            _eoFrame0.setSize(430, 304);
        }
    }
}
